---
title: "Analytics"
output: html_document
---

```{r, message=F, warning=FALSE, error=F}
library(tidyverse)
library(stringr)
library(rebus)
library(readxl)
library(writexl)

theme_set(theme_bw() +
            theme(strip.background = element_blank(),
                  strip.text = element_text(colour = "black", face = "bold"),
                  axis.title = element_text(size = 13, face = "bold", colour = "black"),
                  axis.text = element_text(size = 12, colour = "black"),
                  legend.title = element_text(size = 13),
                  legend.text = element_text(size = 13),
                  panel.grid = element_blank()))

```


# Nov 9~13 2020 two sequence LCMS stability test
```{r, message=F, warning=FALSE, error=F}
# Examine standard tracker
d.tracker = read_excel(path = "/Users/Boyuan/Desktop/Harvard/Research/Karen's project/Nov 2020 KO/standard trackers.xlsx", sheet = 1)
d.tracker = d.tracker %>%
  select(compound, sample, peakArea)

d.tracker.time = read_excel(path = "/Users/Boyuan/Desktop/Harvard/Research/Karen's project/Nov 2020 KO/standard trackers.xlsx", sheet = 2)
d.tracker.time = d.tracker.time %>% 
  mutate(elapse.hour = ((time - min(time))/3600) %>% as.numeric())

d.tracker = d.tracker %>% left_join(d.tracker.time, by = "sample")

d.tracker = d.tracker %>% 
  group_by(compound) %>%
  mutate(peakArea.norm = peakArea / mean(peakArea))

d.tracker.summary = d.tracker %>%
  group_by(compound) %>%
  summarise(signalRange = max(peakArea)/min(peakArea),
         overalErrorPercentage = sd(peakArea)/mean(peakArea) * 100)

d.tracker$compound %>% n_distinct()
plt.tracjer.1 = 
  d.tracker %>%
  # filter(compound == "Serine") %>%
  ggplot(aes(x = elapse.hour, y = peakArea.norm, color = compound, fill = compound)) +
  
  geom_line(aes(group = compound)) +
  geom_point(size = 2.5, fill = "white", stroke = 2, aes(shape = Seq)) + 
  
  facet_wrap(~compound) +
  coord_cartesian(ylim = c(0.5, 1.5)) +
  theme(strip.text = element_text(size = 10),
        legend.position = "None") +
  scale_shape_manual(values = c(16, 21)) +
  
  geom_ribbon(aes(ymin = 0.8, ymax = 1.20, xmin = 0, xmax = 100), alpha = .1, color = NA, fill = "darkgreen") +
  
  labs(x = "Time elapsed (hours)", y = "Normalized peak area", caption = "Green shaded area: 80~120 % error region; solid and empty circle for 1st and 2nd sequence, respectively") +
  
  geom_text(data = d.tracker.summary, # %>% filter(compound == "Serine"), 
            aes(x = 50, y = 1.4, label = paste("Max ~ min range\nfold change = ", round(signalRange, 2))), 
            color = "black", fontface = "bold", size = 3.5) +
  
  geom_text(data = d.tracker.summary, # %>% filter(compound == "Serine"), 
            aes(x = 50, y = 0.6, label = paste("Overal error % = ", round(overalErrorPercentage, 2))), 
            color = "firebrick", fontface = "bold", size = 4)
```



```{r, message=F, warning=FALSE, error=F, fig.width=16, fig.height=18}
plt.tracjer.1
```


```{r, message=F, warning=FALSE, error=F, fig.width=10, fig.height=8}
# plot 2
plt.tracjer.2 = d.tracker.summary %>%
  ggplot(aes(x = "1", y = overalErrorPercentage, color = compound)) +
  geom_point(alpha = 0) +
  geom_text(aes(label = compound), 
            position = position_jitter(.4, 0), fontface = "bold") +
  geom_rug(color = "darkgreen") +
  scale_y_continuous(breaks = seq(0, 70, 5)) +
  theme(legend.position = "None") +
  labs(x = " ", y = "Peak area overall error percentage ")

ggExtra::ggMarginal(plt.tracjer.2, margins = "y")


```

